@startuml
start
:Пользователь открывает планировщик задач в приложении;
:Пользователь нажимает "Добавить задачу";
:Пользователь вводит детали задачи (название, описание, дата, время);
:Пользователь выбирает категорию задачи;

if (Задача связана с сервисом?) then (Да)
    :Система предлагает релевантные сервисы из каталога;
    :Пользователь выбирает сервис и совершает покупку;
    :Начисляется кэшбэк 5% от суммы заказа;
endif

:Задача сохраняется со статусом "Новая";
:Задача отображается в списке задач;

while (Задача не выполнена?) is (Да)
    :Пользователь может редактировать или удалить задачу;
    :Пользователь может изменить статус задачи;
endwhile

if (Статус задачи = "Выполнена") then (Да)
    :Задача помечается как "Выполнена";
else
    :Задача остается в текущем статусе;
endif

stop
@enduml
